parent: $LVSR/exp/dependency/configs/dependency.yaml
net:
    pointers_weight: 0.6
    input_sources:
        - chars_per_word

    dims_bidir: [640, 640]
    subsample: [1, 1]
    bidir_aggregation: add

    reproduce_rec_weight_init_bug: false
    use_dependent_words_for_labels: true
    use_dependent_words_for_attention: true

    dec_transition: !!python/name:lvsr.bricks.FakeRecurrent

    bottom:
        char_to_word_conf:
            character_embedding_dim: 15
            filters:
              - [1, 25]
              - [2, 50]
              - [3, 75]
              - [4, 100]
              - [5, 125]
              - [6, 150]

            filter_activation: 'Tanh()'
            mask_padding_characters: false
            project_dim: 512

            num_highway_layers: 3

regularization:
    dropout:
        encoder: 0.7
        bottom: 0.2

stages:
    pretraining:
        number: 0
        regularization:
            max_norm: 0.0
        training:
            num_epochs: 150
