parent: $LVSR/exp/dependency/configs/universal/base.yaml
data:
    dataset_filename: dependency_hi.h5
    sources_map:
        adptype: adptype
        advtype: advtype
        aspect: aspect
        case: case
        echo: echo
        foreign: foreign
        gender: gender
        mood: mood
        negative: negative
        number: number
        numtype: numtype
        person: person
        polite: polite
        pos: pos
        poss: poss
        prontype: prontype
        tense: tense
        verbform: verbform
        voice: voice
net:
    additional_sources:
        - pointers
        - adptype
        - advtype
        - aspect
        - case
        - echo
        - foreign
        - gender
        - mood
        - negative
        - number
        - numtype
        - person
        - polite
        - pos
        - poss
        - prontype
        - tense
        - verbform
        - voice
